/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectAddContributionRouteImport } from './routes/redirect-add-contribution'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContributorsRouteImport } from './routes/_authenticated/contributors'
import { Route as AuthenticatedContributionsRouteImport } from './routes/_authenticated/contributions'
import { Route as AuthenticatedAddContributionRouteImport } from './routes/_authenticated/add-contribution'

const RedirectAddContributionRoute = RedirectAddContributionRouteImport.update({
  id: '/redirect-add-contribution',
  path: '/redirect-add-contribution',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContributorsRoute =
  AuthenticatedContributorsRouteImport.update({
    id: '/contributors',
    path: '/contributors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContributionsRoute =
  AuthenticatedContributionsRouteImport.update({
    id: '/contributions',
    path: '/contributions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAddContributionRoute =
  AuthenticatedAddContributionRouteImport.update({
    id: '/add-contribution',
    path: '/add-contribution',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/redirect-add-contribution': typeof RedirectAddContributionRoute
  '/add-contribution': typeof AuthenticatedAddContributionRoute
  '/contributions': typeof AuthenticatedContributionsRoute
  '/contributors': typeof AuthenticatedContributorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRoute
  '/reports': typeof AuthenticatedReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/redirect-add-contribution': typeof RedirectAddContributionRoute
  '/add-contribution': typeof AuthenticatedAddContributionRoute
  '/contributions': typeof AuthenticatedContributionsRoute
  '/contributors': typeof AuthenticatedContributorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRoute
  '/reports': typeof AuthenticatedReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/redirect-add-contribution': typeof RedirectAddContributionRoute
  '/_authenticated/add-contribution': typeof AuthenticatedAddContributionRoute
  '/_authenticated/contributions': typeof AuthenticatedContributionsRoute
  '/_authenticated/contributors': typeof AuthenticatedContributorsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/redirect-add-contribution'
    | '/add-contribution'
    | '/contributions'
    | '/contributors'
    | '/dashboard'
    | '/events'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/redirect-add-contribution'
    | '/add-contribution'
    | '/contributions'
    | '/contributors'
    | '/dashboard'
    | '/events'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/redirect-add-contribution'
    | '/_authenticated/add-contribution'
    | '/_authenticated/contributions'
    | '/_authenticated/contributors'
    | '/_authenticated/dashboard'
    | '/_authenticated/events'
    | '/_authenticated/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RedirectAddContributionRoute: typeof RedirectAddContributionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirect-add-contribution': {
      id: '/redirect-add-contribution'
      path: '/redirect-add-contribution'
      fullPath: '/redirect-add-contribution'
      preLoaderRoute: typeof RedirectAddContributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contributors': {
      id: '/_authenticated/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof AuthenticatedContributorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contributions': {
      id: '/_authenticated/contributions'
      path: '/contributions'
      fullPath: '/contributions'
      preLoaderRoute: typeof AuthenticatedContributionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add-contribution': {
      id: '/_authenticated/add-contribution'
      path: '/add-contribution'
      fullPath: '/add-contribution'
      preLoaderRoute: typeof AuthenticatedAddContributionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAddContributionRoute: typeof AuthenticatedAddContributionRoute
  AuthenticatedContributionsRoute: typeof AuthenticatedContributionsRoute
  AuthenticatedContributorsRoute: typeof AuthenticatedContributorsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAddContributionRoute: AuthenticatedAddContributionRoute,
  AuthenticatedContributionsRoute: AuthenticatedContributionsRoute,
  AuthenticatedContributorsRoute: AuthenticatedContributorsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RedirectAddContributionRoute: RedirectAddContributionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
